import { Layout } from './layout';
import { SvgTemplate } from './svgTemplate';
import { Alignment, AlignmentsByCtgs } from '@linkview/linkview-align-parser';

export type DrawOptionsItem = {
  chro_thickness: number;
  no_label: boolean;
  label_font_size: number;
  label_angle: number;
  label_pos: 'center'| 'left' | 'right';
  chro_axis: boolean;
  chro_axis_unit: number | 'auto';
  chro_axis_pos: 'top' | 'bottom' | 'both';
  gap_length: number;
  align: 'center' | 'left' | 'right';
  label_x_offset: number;
  label_y_offset: number;
};
export type IntervalInfoByAlignments = {[ctg: string]: {start: number, end: number}};

export type Options = {
  inputs?: string[];
  inputContent?: string;
  min_alignment_length: number;
  min_identity: number;
  min_bit_score: number;
  max_evalue: number;
  chro_thickness: number;
  no_label: boolean;
  label_font_size: number;
  label_angle: number;
  label_pos: 'center'| 'left' | 'right';
  label_x_offset: number;
  label_y_offset: number;
  gap_length: number;
  svg_height: number;
  svg_width: number;
  svg_content_width: number;
  svg_space: number;
  karyotype?: string;
  karyotypeContent?: string;
  highlight?: string[];
  highlightContent?: string;
  hl_min1px?: boolean;
  gff?: string[];
  gffContent?: string;
  scale?: number;
  show_scale: boolean;
  chro_axis?: boolean;
  chro_axis_unit: number | 'auto';
  chro_axis_pos: 'top' | 'bottom' | 'both';
  align: 'center' | 'left' | 'right';
  parameter?: string;
  parameterContent?: string;
  layout: Layout;
  svg_template?: SvgTemplate;
  svg?: string;
  use: <T>(plugin: (...args: any) => void) => Promise<T> | void;
  drawOptions?: DrawOptionsItem[];
  defualtDrawOptionsItem?: DrawOptionsItem;
  getDrawOptionsItem?: (index: number) => DrawOptionsItem;
  alignments: Alignment[];
  lenInfo: {[ctg: string]: number};
  alignmentsByCtgs: AlignmentsByCtgs;
  bezier?: boolean;
  style: 'classic' | 'simple';
  intervalInfoByAlignments: IntervalInfoByAlignments;
  output?: string;
}
